# wrangler.toml
name = "whois-query"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# 静态文件配置
[site]
bucket = "./public"  # 静态文件目录
# include = ["*"]    # 可选：包含哪些文件
# exclude = ["*.log"] # 可选：排除哪些文件

# 可选：设置环境变量
[env.production]
name = "whois-query-prod"

[env.staging]
name = "whois-query-staging"

# 可选：KV存储配置（如果需要）
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"